# schema.act is generated by rfcgen.act by reading the YANG RFC 7950, which is
# stored in the rfc module.

all: src/schema.act
	acton build

.PHONY: gen
gen: src/schema.act

src/schema.act: gen/schema-header.act gen/schema-footer.act gen/out/bin/rfcgen
	cd gen && out/bin/rfcgen > ../src/schema.act

gen/out/bin/rfcgen: gen/src/rfcgen.act
	cd gen && acton build

.PHONY: clean
clean:
	rm -rf out

.PHONY: test
test:
	acton test
	$(MAKE) test-daclass
	$(MAKE) test-data-source-roundtrip

.PHONY: test-daclass-gen
test-daclass-gen:
	cd test/test_data_classes_gen && acton build && out/bin/gen

.PHONY: test-daclass
test-daclass: test-daclass-gen
	cd test/test_data_classes && acton test

.PHONY: test-data-source-roundtrip
test-data-source-roundtrip:
	cd test/test_data_source_roundtrip && acton test

.PHONY: test-yang-compile
test-yang-compile:
# TODO: use --release=safe here, after issues UB issues have been resolved / Acton codegen peculiarities added to sanitize exceptions
	cd test/test_yang_compile && acton test --max-time 600000 --min-iter 1 --max-iter 1 --release=fast

.PHONY: test-accept
test-accept:
	acton test --accept
	cd test/test_data_classes_gen && acton build && out/bin/gen
	cd test/test_data_classes && acton test --accept
	cd test/test_data_source_roundtrip && acton test --accept

test-yang-compile-accept:
	cd test/test_yang_compile && acton test --max-time 600000 --min-iter 1 --max-iter 1 --release=fast --accept
